### PR TITLE
feature: Helm chart for Kubernetes deployment 

### PR DESCRIPTION
**Pull request by tolbrino**
Make sure these boxes are checked! 📦✅

- [x] You have a nightly compatible version of `rustfmt` installed
```bash
rustup component add rustfmt --toolchain nightly
```
- [x] You ran `cargo +nightly fmt` on the code base before submitting

### What was wrong? 👾

The repository was lacking a Helm chart for Kubernetes deployment.

### How was it fixed? 🎯

The Helm chart was added at `charts/safe-client-gateway`, a location adhering to Helm best-practises. The helper script at `scripts/build-and-publish-helm-chart.sh` can be used for releasing new versions of the Helm chart. Documentation of the chart is at `charts/safe-client-gateway`.

This chart is already used successfully to run the Safe infrastructure in Kubernetes.

## Sibling PRs

- https://github.com/safe-global/safe-wallet-web/pull/2330
- https://github.com/safe-global/safe-transaction-service/pull/1601
- https://github.com/safe-global/safe-config-service/pull/911

### CODE REVIEW

**Comment by tolbrino** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by tolbrino** [comment]
recheck

**Comment by fmrsabino** [comment]
@tolbrino and @ausias-armesto thank you for your contribution.

> The repository was lacking a Helm chart for Kubernetes deployment.

This is not something that we need for the project. My recommendation is to fork the repository and change it according to your needs.

At the moment we won't specify on how the service should be deployed and the respective resources (that is up to each team using it). This applies to the suggested kubernetes configuration.

**Comment by tolbrino** [comment]
> @tolbrino and @ausias-armesto thank you for your contribution.
> 
> > The repository was lacking a Helm chart for Kubernetes deployment.
> 
> This is not something that we need for the project. My recommendation is to fork the repository and change it according to your needs.
> 
> At the moment we won't specify on how the service should be deployed and the respective resources (that is up to each team using it). This applies to the suggested kubernetes configuration.

Thanks for the feedback. We are already working with our own forks, but that does not help out the Safe community as a whole since discovery of such additional changes is hard.

I understand you might not want to add these files into each repository. How about creating a new repository called `safe-charts` which holds all available charts for the various Safe infrastructure components? You may then also state that the repository is a community effort and not an official distribution, but at least its a single place for the community to find it.

**Comment by fmrsabino** [comment]
> Thanks for the feedback. We are already working with our own forks, but that does not help out the Safe community as a whole since discovery of such additional changes is hard.

We try to address the community needs including feature-discovery. However a discussion about those needs is also required. The introduction of this tool and respective deployment files assumes that this how the project should be deployed and these tools should be used. We do not make any assumptions on how the deployment should work in this repo and we give that choice to the developers who want to run our services themselves. We do provide a Docker image to make it easier to deploy but even then we do not assume that the image itself should be used (e.g. a developer/team might want to use a competing solution to Docker).

> I understand you might not want to add these files into each repository. How about creating a new repository called `safe-charts` which holds all available charts for the various Safe infrastructure components? You may then also state that the repository is a community effort and not an official distribution, but at least its a single place for the community to find it.

If the suggestion is for it to live under the `safe-global` then this needs to be aligned internally. However, due to the open-source nature of the project, something like `safe-charts` can be created by any org. I cannot promise that this is something that will be done under `safe-global` (for the reasons that I mentioned).

Also, there was no discussion on why this change is necessary for the project and an evaluation on the community support behind it. Adding Helm to the repository assumes that Helm is the desired solution that we want for the community and so far that discussion did not take place. Since this repository mostly deals with the business logic for client-side rendering, the respective deployment of such service should in this case be considered on a separate repo (as you suggested).

**Pull request closed without merging**
